/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.view;

import org.example.controller.ViewController;

/**
 *
 * @author ericp
 */
public class PanelMain extends javax.swing.JPanel {

    /**
     * Creates new form PanelMain
     */
    public PanelMain() {
        initComponents();
        this.setSize(800,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttnEmployee = new javax.swing.JButton();
        bttnCarrier = new javax.swing.JButton();
        bttnSupplier = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        bttnReport = new javax.swing.JButton();
        bttnWarehouse = new javax.swing.JButton();
        bttnOrder = new javax.swing.JButton();
        bttnProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 150));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        bttnEmployee.setBackground(new java.awt.Color(0, 0, 102));
        bttnEmployee.setForeground(new java.awt.Color(204, 255, 255));
        bttnEmployee.setText("EMPLEADO");
        bttnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEmployeeActionPerformed(evt);
            }
        });

        bttnCarrier.setBackground(new java.awt.Color(0, 0, 102));
        bttnCarrier.setForeground(new java.awt.Color(204, 255, 255));
        bttnCarrier.setText("TRANSPORTISTA");
        bttnCarrier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCarrierActionPerformed(evt);
            }
        });

        bttnSupplier.setBackground(new java.awt.Color(0, 0, 102));
        bttnSupplier.setForeground(new java.awt.Color(204, 255, 255));
        bttnSupplier.setText("PROVEEDOR");
        bttnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSupplierActionPerformed(evt);
            }
        });

        btnCustomer.setBackground(new java.awt.Color(0, 0, 102));
        btnCustomer.setForeground(new java.awt.Color(204, 255, 255));
        btnCustomer.setText("CLIENTE");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        bttnReport.setBackground(new java.awt.Color(0, 0, 102));
        bttnReport.setForeground(new java.awt.Color(204, 255, 255));
        bttnReport.setText("INFORME");
        bttnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnReportActionPerformed(evt);
            }
        });

        bttnWarehouse.setBackground(new java.awt.Color(0, 0, 102));
        bttnWarehouse.setForeground(new java.awt.Color(204, 255, 255));
        bttnWarehouse.setText("DÉPOSITO");
        bttnWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnWarehouseActionPerformed(evt);
            }
        });

        bttnOrder.setBackground(new java.awt.Color(0, 0, 102));
        bttnOrder.setForeground(new java.awt.Color(204, 255, 255));
        bttnOrder.setText("PEDIDO");
        bttnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnOrderMouseClicked(evt);
            }
        });

        bttnProduct.setBackground(new java.awt.Color(0, 0, 102));
        bttnProduct.setForeground(new java.awt.Color(204, 255, 255));
        bttnProduct.setText("PRODUCTO");
        bttnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnProductActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("BIENVENIDO A LDE SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(bttnWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnCarrier, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnCarrier, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        ViewController.panelChange(this, new PanelCustomer(), this);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void bttnCarrierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCarrierActionPerformed
       ViewController.panelChange(this, new PanelCarrier(), this);
    }//GEN-LAST:event_bttnCarrierActionPerformed


    private void bttnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSupplierActionPerformed
            ViewController.panelChange(this, new PanelSupplier(), this);

    }//GEN-LAST:event_bttnSupplierActionPerformed

    private void bttnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEmployeeActionPerformed
        ViewController.panelChange(this, new PanelEmployee(), this);
    }//GEN-LAST:event_bttnEmployeeActionPerformed
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void bttnOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnOrderMouseClicked
        ViewController.panelChange(this, new PanelOrder(), this);
    }//GEN-LAST:event_bttnOrderMouseClicked

    private void bttnWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnWarehouseActionPerformed
        ViewController.panelChange(this, new PanelWarehouse(), this);
    }//GEN-LAST:event_bttnWarehouseActionPerformed

    private void bttnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnReportActionPerformed
        ViewController.panelChange(this, new PanelReport(), this);
    }//GEN-LAST:event_bttnReportActionPerformed

    private void bttnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnProductActionPerformed
        ViewController.panelChange(this, new PanelProduct(), this);
    }//GEN-LAST:event_bttnProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton bttnCarrier;
    private javax.swing.JButton bttnEmployee;
    private javax.swing.JButton bttnOrder;
    private javax.swing.JButton bttnProduct;
    private javax.swing.JButton bttnReport;
    private javax.swing.JButton bttnSupplier;
    private javax.swing.JButton bttnWarehouse;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
