/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.example.controller.CarrierController;
import org.example.controller.ViewController;
import org.example.model.Carrier;
import org.example.model.Carrier.CarrierType;

/**
 *
 * @author Usuario
 */
public class PanelCarrierEdit extends javax.swing.JPanel {
    private final String cuit;
    private final CarrierController carrierController;
    private Carrier carrierEdit;

    /**
     * Creates new form PanelCarrierEdit
     * @param cuit
     */
    public PanelCarrierEdit(String cuit) {
        carrierController = new CarrierController();
        carrierEdit = new Carrier();
        this.cuit = cuit;
        initComponents();
        this.setSize(800,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcomeCarrier = new javax.swing.JLabel();
        lblComplement = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblCuit1 = new javax.swing.JLabel();
        txtCuit = new javax.swing.JTextField();
        lblTel = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jlblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jlblEmail1 = new javax.swing.JLabel();
        cmbTranspEdit = new javax.swing.JComboBox<>();
        bttnModif = new javax.swing.JButton();
        bttnCancel = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblWelcomeCarrier.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblWelcomeCarrier.setText("MODIFICAR TRANSPORTISTA");

        lblComplement.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        lblComplement.setText("Por favor ingrese los nuevos datos");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName.setText("Nombre");

        txtName.setVerifyInputWhenFocusTarget(false);

        lblCuit1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCuit1.setText("Cuit");

        txtCuit.setVerifyInputWhenFocusTarget(false);

        lblTel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTel.setText("Telefono");

        txtTel.setVerifyInputWhenFocusTarget(false);

        jlblEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlblEmail.setText("Email");

        jlblEmail1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlblEmail1.setText("Tipo");

        cmbTranspEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<seleccionar>", "Maritimo", "Terrestre", "Aereo" }));
        cmbTranspEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTranspEditActionPerformed(evt);
            }
        });

        bttnModif.setBackground(new java.awt.Color(0, 102, 255));
        bttnModif.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        bttnModif.setForeground(new java.awt.Color(255, 255, 255));
        bttnModif.setText("Modificar");
        bttnModif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnModifActionPerformed(evt);
            }
        });

        bttnCancel.setBackground(new java.awt.Color(204, 0, 0));
        bttnCancel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        bttnCancel.setForeground(new java.awt.Color(255, 255, 255));
        bttnCancel.setText("Cancelar");
        bttnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(lblWelcomeCarrier)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lblComplement))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttnModif, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                            .addComponent(lblCuit1)
                            .addComponent(txtCuit, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                            .addComponent(lblTel)
                            .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                            .addComponent(jlblEmail)
                            .addComponent(txtEmail)
                            .addComponent(jlblEmail1)
                            .addComponent(cmbTranspEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblWelcomeCarrier)
                .addGap(32, 32, 32)
                .addComponent(lblComplement)
                .addGap(23, 23, 23)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblCuit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jlblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblEmail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTranspEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnModif, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTranspEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTranspEditActionPerformed

    }//GEN-LAST:event_cmbTranspEditActionPerformed

    private void bttnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnModifActionPerformed
        if(!(txtName.getText().isEmpty()|| txtTel.getText().isEmpty() || txtCuit.getText().isEmpty() || null == cmbTranspEdit.getSelectedItem())){
            carrierEdit.setName(txtName.getText());
            carrierEdit.setCuit(txtCuit.getText());
            carrierEdit.setPhone(txtTel.getText());
            carrierEdit.setEmail(txtEmail.getText());
            carrierEdit.setType(loadCarrierType());
            try {
                carrierController.upDate(carrierEdit);
            } catch (Exception ex) {
                Logger.getLogger(PanelCarrierEdit.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Transportista modificado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            ViewController.panelChange(this, new PanelCarrierConsult(), this);
        } else{
            JOptionPane.showMessageDialog(null, "Un campo no puede estar vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bttnModifActionPerformed

    
    
    private void bttnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelActionPerformed
        ViewController.panelChange(this, new PanelCarrierConsult(), this);
        
    }//GEN-LAST:event_bttnCancelActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        loadData(cuit);
    }//GEN-LAST:event_formAncestorAdded
    private CarrierType loadCarrierType(){
        if (cmbTranspEdit.getSelectedItem() == "Aereo"){
            return Carrier.CarrierType.AIR;
        }else if(cmbTranspEdit.getSelectedItem() == "Maritimo"){
            return Carrier.CarrierType.MARITIME;
        }else if(cmbTranspEdit.getSelectedItem() == "Terrestre"){
            return Carrier.CarrierType.LAND;
        }
        return null;
    }
    private String loadCmbTranspEdit(String cuit){
        Carrier carrierLoad = carrierController.findOne(cuit);
    if (carrierLoad.getType().equals(Carrier.CarrierType.AIR)){
            return "Aereo";
        }else if(carrierLoad.getType().equals(Carrier.CarrierType.MARITIME)){
            return "Maritimo";
        }else if(carrierLoad.getType().equals(Carrier.CarrierType.LAND)){
            return "Terrestre";
        }
        return null;
    }
    
    
    public void loadData(String cuit){
        carrierEdit = carrierController.findOne(cuit);
        txtCuit.setText(carrierEdit.getCuit());
        txtName.setText(carrierEdit.getName());
        txtTel.setText(carrierEdit.getPhone());
        txtEmail.setText(carrierEdit.getEmail());
        cmbTranspEdit.setSelectedItem(loadCmbTranspEdit(cuit));
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCancel;
    private javax.swing.JButton bttnModif;
    private javax.swing.JComboBox<String> cmbTranspEdit;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblEmail1;
    private javax.swing.JLabel lblComplement;
    private javax.swing.JLabel lblCuit1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblWelcomeCarrier;
    private javax.swing.JTextField txtCuit;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
