/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.view;

import org.example.controller.ViewController;

/**
 *
 * @author facundo
 */
public class PanelEmployee extends javax.swing.JPanel {

    /**
     * Creates new form PanelEmployee
     */
    public PanelEmployee() {
        initComponents();
        this.setSize(800,700);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttnBack = new javax.swing.JButton();
        bttnConsultEmployee = new javax.swing.JButton();
        bttnCreateEmployee = new javax.swing.JButton();
        bttnComplement = new javax.swing.JLabel();
        lblPresent = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 150));

        bttnBack.setBackground(new java.awt.Color(217, 74, 51));
        bttnBack.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bttnBack.setForeground(new java.awt.Color(204, 255, 255));
        bttnBack.setText("SALIR");
        bttnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBackActionPerformed(evt);
            }
        });

        bttnConsultEmployee.setBackground(new java.awt.Color(0, 0, 102));
        bttnConsultEmployee.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bttnConsultEmployee.setForeground(new java.awt.Color(0, 195, 225));
        bttnConsultEmployee.setText("CONSULTAR,MODIFICAR,ELIMINAR");
        bttnConsultEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bttnConsultEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConsultEmployeeActionPerformed(evt);
            }
        });

        bttnCreateEmployee.setBackground(new java.awt.Color(0, 0, 102));
        bttnCreateEmployee.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bttnCreateEmployee.setForeground(new java.awt.Color(0, 195, 225));
        bttnCreateEmployee.setText("CREAR EMPLEADO");
        bttnCreateEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bttnCreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCreateEmployeeActionPerformed(evt);
            }
        });

        bttnComplement.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bttnComplement.setForeground(new java.awt.Color(232, 245, 255));
        bttnComplement.setText("Por favor seleccione la opcion que desee");

        lblPresent.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(232, 245, 255));
        lblPresent.setText("Gestion de EMPLEADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPresent)
                    .addComponent(bttnComplement))
                .addGap(182, 182, 182))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnConsultEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnCreateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblPresent)
                .addGap(87, 87, 87)
                .addComponent(bttnComplement)
                .addGap(43, 43, 43)
                .addComponent(bttnCreateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(bttnConsultEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBackActionPerformed
        ViewController.panelChange(this,  new PanelMain(), this);
    }//GEN-LAST:event_bttnBackActionPerformed

    private void bttnConsultEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConsultEmployeeActionPerformed
        ViewController.panelChange(this, new PanelEmployeeConsult(), this);
    }//GEN-LAST:event_bttnConsultEmployeeActionPerformed

    private void bttnCreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCreateEmployeeActionPerformed
        ViewController.panelChange(this,new PanelEmployeeCreate() , this);
    }//GEN-LAST:event_bttnCreateEmployeeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnBack;
    private javax.swing.JLabel bttnComplement;
    private javax.swing.JButton bttnConsultEmployee;
    private javax.swing.JButton bttnCreateEmployee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPresent;
    // End of variables declaration//GEN-END:variables
}
