/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.example.controller.ViewController;
import org.example.controller.WarehouseController;
import org.example.model.Warehouse;

/**
 *
 * @author ericp
 */
public class PanelCreateOrder2 extends javax.swing.JPanel {
    private String cuitCustomer;
    private String cuitCarrier;
    private ViewController viewController;
    private WarehouseController warehouseController;
    

    /**
     * Creates new form PanelCreateOrder1
     */
    public PanelCreateOrder2(String cuitCostumer, String cuitCarrier) {
        this.cuitCarrier = cuitCarrier;
        this.cuitCustomer = cuitCostumer;
        this.warehouseController = new WarehouseController();
        this.viewController = new ViewController();
        this.cuitCarrier = cuitCarrier;
        this.cuitCustomer = cuitCostumer;
        this.setSize(800,700);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblOrig = new javax.swing.JLabel();
        txtOrig = new javax.swing.JTextField();
        bttnWarehouseOrig = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblWarehouseOrig = new javax.swing.JTable();
        lblDest = new javax.swing.JLabel();
        txtDEST = new javax.swing.JTextField();
        bttnWarehouseDest = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblWarehouseDest = new javax.swing.JTable();
        bttnBack = new javax.swing.JButton();
        bttnConfirm = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblWelcome.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 0, 0));
        lblWelcome.setText("SELECCIONAR DÉPOSITOS");

        lblOrig.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblOrig.setForeground(new java.awt.Color(0, 0, 0));
        lblOrig.setText("Origen");

        bttnWarehouseOrig.setText("Buscar");
        bttnWarehouseOrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnWarehouseOrigActionPerformed(evt);
            }
        });

        tblWarehouseOrig.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblWarehouseOrig);

        lblDest.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblDest.setForeground(new java.awt.Color(0, 0, 0));
        lblDest.setText("Destino");

        txtDEST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDESTActionPerformed(evt);
            }
        });

        bttnWarehouseDest.setText("Buscar");
        bttnWarehouseDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnWarehouseDestActionPerformed(evt);
            }
        });

        tblWarehouseDest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblWarehouseDest);

        bttnBack.setBackground(new java.awt.Color(204, 0, 0));
        bttnBack.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        bttnBack.setForeground(new java.awt.Color(255, 255, 255));
        bttnBack.setText("Cancelar");
        bttnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBackActionPerformed(evt);
            }
        });

        bttnConfirm.setBackground(new java.awt.Color(0, 102, 255));
        bttnConfirm.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        bttnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        bttnConfirm.setText("Siguiente");
        bttnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(bttnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrig, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtOrig, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttnWarehouseOrig)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDEST, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttnWarehouseDest)
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblWelcome))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblOrig))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOrig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttnWarehouseOrig))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDest)
                    .addComponent(bttnWarehouseDest)
                    .addComponent(txtDEST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnWarehouseOrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnWarehouseOrigActionPerformed
        tblWarehouseOrig.setModel(viewController.modelTableWarehousesByEmail(txtOrig.getText()));
        
    }//GEN-LAST:event_bttnWarehouseOrigActionPerformed

    private void txtDESTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDESTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDESTActionPerformed

    private void bttnWarehouseDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnWarehouseDestActionPerformed
        tblWarehouseDest.setModel(viewController.modelTableWarehousesByEmail(txtDEST.getText()));

    }//GEN-LAST:event_bttnWarehouseDestActionPerformed

    private void bttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBackActionPerformed
        ViewController.panelChange(this, new PanelCreateOrder1(), this);
    }//GEN-LAST:event_bttnBackActionPerformed

    private void bttnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConfirmActionPerformed
        List<Warehouse> warehouses = warehouseController.warehousesIdForOrder(tblWarehouseOrig, tblWarehouseDest);
        if(warehouses.size()<2){
             JOptionPane.showMessageDialog(this, "Seleccione los depositos!", "Error", JOptionPane.ERROR_MESSAGE);

        } else{
                    ViewController.panelChange(this, new PanelCreateOrder3(cuitCustomer, cuitCarrier, warehouses.get(0), warehouses.get(1)), this);

        }
    }//GEN-LAST:event_bttnConfirmActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        this.loadData();
    }//GEN-LAST:event_formAncestorAdded
    public void loadData(){
        this.tblWarehouseDest.setModel(viewController.modelTableWarehouses());
        this.tblWarehouseOrig.setModel(viewController.modelTableWarehouses());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnBack;
    private javax.swing.JButton bttnConfirm;
    private javax.swing.JButton bttnWarehouseDest;
    private javax.swing.JButton bttnWarehouseOrig;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblDest;
    private javax.swing.JLabel lblOrig;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblWarehouseDest;
    private javax.swing.JTable tblWarehouseOrig;
    private javax.swing.JTextField txtDEST;
    private javax.swing.JTextField txtOrig;
    // End of variables declaration//GEN-END:variables
}
