/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.view;

import org.example.controller.ViewController;

/**
 *
 * @author facundo
 */
public class PanelSupplier extends javax.swing.JPanel {

    /**
     * Creates new form PanelSupplier
     */
    public PanelSupplier() {
        initComponents();
        this.setSize(800,700);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttnBack = new javax.swing.JButton();
        bttnConsultCustomer = new javax.swing.JButton();
        bttnCreateCustomer = new javax.swing.JButton();
        bttnComplement = new javax.swing.JLabel();
        lblPresent = new javax.swing.JLabel();

        bttnBack.setBackground(new java.awt.Color(217, 74, 51));
        bttnBack.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bttnBack.setForeground(new java.awt.Color(204, 255, 255));
        bttnBack.setText("SALIR");
        bttnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBackActionPerformed(evt);
            }
        });

        bttnConsultCustomer.setBackground(new java.awt.Color(0, 0, 102));
        bttnConsultCustomer.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bttnConsultCustomer.setForeground(new java.awt.Color(0, 195, 225));
        bttnConsultCustomer.setText("CONSULTAR,MODIFICAR,ELIMINAR");
        bttnConsultCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bttnConsultCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConsultCustomerActionPerformed(evt);
            }
        });

        bttnCreateCustomer.setBackground(new java.awt.Color(0, 0, 102));
        bttnCreateCustomer.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bttnCreateCustomer.setForeground(new java.awt.Color(0, 195, 225));
        bttnCreateCustomer.setText("CREAR PROVEEDOR");
        bttnCreateCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bttnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCreateCustomerActionPerformed(evt);
            }
        });

        bttnComplement.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bttnComplement.setForeground(new java.awt.Color(232, 245, 255));
        bttnComplement.setText("Por favor seleccione la opcion que desee");

        lblPresent.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(232, 245, 255));
        lblPresent.setText("Gestion de Proveedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPresent)
                    .addComponent(bttnComplement))
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnConsultCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblPresent)
                .addGap(87, 87, 87)
                .addComponent(bttnComplement)
                .addGap(43, 43, 43)
                .addComponent(bttnCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(bttnConsultCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(bttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBackActionPerformed
        ViewController.panelChange(this, new PanelMain(), this);
    }//GEN-LAST:event_bttnBackActionPerformed

    private void bttnConsultCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConsultCustomerActionPerformed
        ViewController.panelChange(this, new PanelSupplierConsult(), this);
    }//GEN-LAST:event_bttnConsultCustomerActionPerformed

    private void bttnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCreateCustomerActionPerformed
        ViewController.panelChange(this, new PanelSupplierCreate(), this);
    }//GEN-LAST:event_bttnCreateCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnBack;
    private javax.swing.JLabel bttnComplement;
    private javax.swing.JButton bttnConsultCustomer;
    private javax.swing.JButton bttnCreateCustomer;
    private javax.swing.JLabel lblPresent;
    // End of variables declaration//GEN-END:variables
}
